#!/bin/bash

items=
for i in "$@"
do
    items="$items \"$i\""
done
for i in $items
do
    echo $i
done


eval set -- $items
for i in "$@"
do
    echo $i
done

set -x
set -- $items
set +x
echo '===='
set -x
eval set -- $items
set +x

